# Redis won't be used if not a networking server

server-id: example
min-rank: PLAYER

redis:
  host: host
  port: port
  auth: auth

mysql:
  host: localhost
  port: 3306
  username: username
  password: password
  database: db

mongo:
  host: localhost
  port: 27017
  udatabase: udb
  username: username
  password: password
  database: db

